# Actuator config
management:
  server:
    port: 9097
  info:
    env:
      enabled: true
  health:
    mongo:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: "${spring.application.name}"