version: '3'
services:
  postgres:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=stc
      - POSTGRES_PASSWORD=stc_assessments
      - POSTGRES_DB=filemanager
#    environment:
#      - POSTGRES_USER=$POSTGRES_USERNAME
#      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
#      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  filemanager:
    container_name: filemanager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 9092:9092
    restart: on-failure
    depends_on:
      - postgres
volumes:
  pgdata:
