version: '3'
services:
#  filemanager:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
  postgres:
    container_name: filemanager_pq
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: stc
      POSTGRES_PASSWORD: stc_assessments
      POSTGRES_DB: filemanager
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
