# App
server:
  port: 8087

spring:
  application:
    name: "@project.name@"
  config:
    import:
      - "classpath:properties/logging-configs.yml"
      - "classpath:properties/api-docs.yml"
      - "classpath:properties/actuator-configs.yml"
  zipkin:
    enabled: ${ZIPKIN_ENABLED}
    baseUrl: ${ZIPKIN_BASE_URL}

  datasource:
    url: "jdbc:postgresql://localhost:5432/filemanager"
    username: stc
    password: stc_assessments

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
flyway:
  locations: db/migration/postgresql
  baselineOnMigrate: true

# Info endpoint config
info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"
    contact:
      name: File manager - STC assesstments
      url: https://gotrah.com
      email: rowan.ibrahim.mohsen@gmail.com
    termsOfService: TOC
    license:
      name: Apache License Version 2.0
      url: http://www.apache.org/licenses/LICENSE-2.0
    ingressPath: ${INGRESS_PATH}

constants:
  spaceName: stc-assessments
  userViewer: user1@example.com
  userEditor: user2@example.com
  userAdmin: admin
